// Copy this file to `config.js` (gitignored) and set your Clerk
// publishable key. For production deploys, the `config.js` file is
// generated by the GitHub Actions workflow from the `CLERK_PUBLISHABLE_KEY`
// repository secret — do not commit it.
//
// Publishable keys are safe to expose in client code; they identify the
// Clerk instance but do not grant any backend privileges.

window.CLERK_CONFIG = {
  publishableKey: 'pk_REPLACE_ME',
};
